import LegalDocument from "../_components/LegalDocument";

export const metadata = { title: "Terms of Service — CYPHERYN", description: "Terms governing lawful and authorized use of CYPHERYN." };

export default function TermsPage() {
  return <LegalDocument title="CYPHERYN Terms of Service" version="1.0">
    <section><h2>1. Purpose</h2><p>CYPHERYN provides technology for lawful defensive cybersecurity, authorized security testing, open-source intelligence, attack-surface analysis, threat intelligence, security research, and investigations of assets the user owns or is expressly authorized to assess.</p></section>
    <section><h2>2. Authorized use</h2><p><strong>CYPHERYN may only be used to assess systems, networks, accounts, infrastructure, organizations, data, or other assets that you own or are expressly authorized to investigate or test.</strong> You are responsible for obtaining and retaining appropriate authorization before collection begins.</p><p>Access to CYPHERYN does not constitute authorization to investigate, scan, test, access, or interact with a third-party system. Authorization must come from the owner or operator, or another legally authorized party.</p></section>
    <section><h2>3. Your responsibilities</h2><p>You are responsible for your activities, submitted targets, initiated scans, collected data, compliance with applicable law and contracts, respect for third-party rights, and the accuracy and sufficiency of your authorization.</p></section>
    <section><h2>4. Prohibited conduct</h2><p>You may not use CYPHERYN for unauthorized access or testing, credential theft, malware distribution, destructive attacks, harassment, stalking, fraud, phishing, identity theft, illegal surveillance, unauthorized collection of private information, circumvention of access controls without authorization, or any other unlawful or abusive activity. This list is not exhaustive.</p></section>
    <section><h2>5. Results and AI-generated material</h2><p>Findings may contain false positives, false negatives, outdated or incomplete information, incorrect correlations, third-party inaccuracies, AI-generated assessments, and inferences rather than established facts. CYPHERYN findings are provided for informational and security-analysis purposes. Independently verify significant findings before taking action. AI-generated material is not a guaranteed fact or a substitute for qualified human judgment.</p></section>
    <section><h2>6. Third-party services and data</h2><p>Third-party services have their own terms and privacy practices. Availability and accuracy are outside CYPHERYN&apos;s control. Separate accounts, API credentials, permissions, or authorization may be required, and you must comply with applicable provider terms.</p></section>
    <section><h2>7. No security guarantee</h2><p>CYPHERYN does not guarantee discovery of every asset, vulnerability, threat, or correct correlation. An absence of findings does not establish that a system is secure. CYPHERYN should be one component of a broader security program.</p></section>
    <section><h2>8. Responsibility and limitations</h2><p>CYPHERYN provides technology for lawful cybersecurity, defensive security, security research, and open-source intelligence purposes. Users are solely responsible for ensuring that their use is authorized and complies with applicable laws, regulations, contractual obligations, and third-party rights.</p><p>To the maximum extent permitted by applicable law, CYPHERYN and its owners, operators, developers, contributors, affiliates, and service providers are not responsible for unauthorized, unlawful, abusive, or otherwise improper use of the platform by users. Nothing here excludes responsibility that cannot lawfully be excluded.</p></section>
    <section><h2>9. Related policies</h2><p>The <a href="/responsible-use">Responsible Use Policy</a> and <a href="/privacy">Privacy Policy</a> form part of this legal framework.</p></section>
  </LegalDocument>;
}
