from __future__ import annotations

import json
import re
import uuid
import zlib
from datetime import UTC, datetime

import yaml
from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import Entity, Investigation, NetworkDetection, ThreatIntelObject

SIGMA_LEVELS = {"informational", "low", "medium", "high", "critical"}
STIX_VALUE = re.compile(
    r"(?P<kind>domain-name|ipv4-addr|ipv6-addr|url):value\s*=\s*['\"](?P<value>[^'\"]+)['\"]",
    re.IGNORECASE,
)


def parse_sigma(content: str) -> dict:
    try:
        document = yaml.safe_load(content)
    except yaml.YAMLError as exc:
        raise ValueError("Sigma YAML is invalid") from exc
    if not isinstance(document, dict):
        raise ValueError("Sigma rule must be a YAML object")
    if not str(document.get("title") or "").strip():
        raise ValueError("Sigma rule requires a title")
    if not isinstance(document.get("logsource"), dict) or not document["logsource"]:
        raise ValueError("Sigma rule requires a logsource")
    detection = document.get("detection")
    if not isinstance(detection, dict) or not detection.get("condition"):
        raise ValueError("Sigma rule requires detection logic and a condition")
    rule_id = str(document.get("id") or uuid.uuid5(uuid.NAMESPACE_URL, content))
    level = str(document.get("level") or "medium").lower()
    return {
        "rule_id": rule_id[:100],
        "title": str(document["title"]).strip()[:300],
        "level": level if level in SIGMA_LEVELS else "medium",
        "logsource": document["logsource"],
        "tags": list(document.get("tags") or [])[:100],
    }


def export_suricata(db: Session, organization_id: str) -> str:
    rules = []
    used_sids: set[int] = set()
    for indicator in db.scalars(
        select(ThreatIntelObject).where(
            ThreatIntelObject.organization_id == organization_id,
            ThreatIntelObject.object_type == "indicator",
            ThreatIntelObject.revoked.is_(False),
        )
    ):
        for match in STIX_VALUE.finditer(indicator.pattern or ""):
            kind, value = match.group("kind").lower(), match.group("value")
            if any(char in value for char in ('"', ";", "\n", "\r")):
                continue
            sid = 4_000_000 + zlib.crc32(f"{indicator.stix_id}:{value}".encode()) % 999_999
            while sid in used_sids:
                sid += 1
            used_sids.add(sid)
            message = f"SignalTrace STIX {indicator.source} {indicator.name}".replace('"', "'")[
                :180
            ]
            if kind == "domain-name":
                body = f'dns.query; content:"{value}"; nocase;'
                header = "alert dns any any -> any any"
            elif kind in {"ipv4-addr", "ipv6-addr"}:
                body = ""
                header = f"alert ip any any -> {value} any"
            else:
                body = f'http.uri; content:"{value}"; nocase;'
                header = "alert http any any -> any any"
            rules.append(f'{header} (msg:"{message}"; {body} sid:{sid}; rev:1;)')
            if len(rules) >= 5000:
                break
        if len(rules) >= 5000:
            break
    return "# Generated by SignalTrace from active STIX indicators\n" + "\n".join(rules) + "\n"


def _time(value: object) -> datetime:
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(float(value), UTC)
    if isinstance(value, str):
        try:
            result = datetime.fromisoformat(value.replace("Z", "+00:00"))
            return result if result.tzinfo else result.replace(tzinfo=UTC)
        except ValueError:
            pass
    return datetime.now(UTC)


def parse_json_lines(data: bytes) -> tuple[list[dict], int]:
    events, skipped = [], 0
    for line in data.decode("utf-8", errors="replace").splitlines()[:5000]:
        if not line.strip() or line.startswith("#"):
            continue
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        if isinstance(event, dict):
            events.append(event)
        else:
            skipped += 1
    return events, skipped


def ingest_network_events(
    db: Session,
    investigation: Investigation,
    source: str,
    data: bytes,
) -> dict:
    events, skipped = parse_json_lines(data)
    entity_map = {
        entity.canonical_value.lower(): entity.id
        for entity in db.scalars(select(Entity).where(Entity.investigation_id == investigation.id))
    }
    imported = correlated = 0
    for event in events:
        if source == "suricata":
            if event.get("event_type") != "alert":
                skipped += 1
                continue
            alert = event.get("alert") if isinstance(event.get("alert"), dict) else {}
            severity_number = int(alert.get("severity") or 3)
            signature = str(alert.get("signature") or "Suricata alert")[:500]
            src_ip, dest_ip = event.get("src_ip"), event.get("dest_ip")
            src_port, dest_port = event.get("src_port"), event.get("dest_port")
            protocol = str(event.get("proto") or "")[:20]
            observed = _time(event.get("timestamp"))
            severity = (
                "high" if severity_number == 1 else "medium" if severity_number == 2 else "low"
            )
            event_type = "alert"
        else:
            src_ip, dest_ip = event.get("id.orig_h"), event.get("id.resp_h")
            src_port, dest_port = event.get("id.orig_p"), event.get("id.resp_p")
            protocol = str(event.get("proto") or "")[:20]
            signature = str(event.get("note") or event.get("_path") or "Zeek network event")[:500]
            observed = _time(event.get("ts"))
            severity = "medium" if event.get("note") else "info"
            event_type = str(event.get("_path") or "network")[:50]
        matches = [
            entity_map[value.lower()]
            for value in (str(src_ip or ""), str(dest_ip or ""))
            if value.lower() in entity_map
        ]
        if matches:
            correlated += 1
        db.add(
            NetworkDetection(
                investigation_id=investigation.id,
                source=source,
                event_type=event_type,
                signature=signature,
                severity=severity,
                src_ip=str(src_ip)[:45] if src_ip else None,
                src_port=int(src_port) if isinstance(src_port, (int, float)) else None,
                dest_ip=str(dest_ip)[:45] if dest_ip else None,
                dest_port=int(dest_port) if isinstance(dest_port, (int, float)) else None,
                protocol=protocol,
                correlated_entity_ids=matches,
                raw_event={key: value for key, value in list(event.items())[:100]},
                observed_at=observed,
            )
        )
        imported += 1
    return {"source": source, "imported": imported, "correlated": correlated, "skipped": skipped}
